.gitignore
pom.xml
src/main/resources/application.properties

added checkstyle plugin in the `pom.xml`
**TODO**: there's lots of lint errors in the style checkers needs to get fixed.

[T3][p0S][1/n] added check style plugin

---

pom.xml
src/main/java/com/lgtm/easymoney/controllers/BalanceController.java
src/main/java/com/lgtm/easymoney/controllers/UserController.java
src/main/java/com/lgtm/easymoney/exceptions/handlers/ControllerExceptionHandler.java
src/main/java/com/lgtm/easymoney/models/Account.java
src/main/java/com/lgtm/easymoney/models/Transaction.java
src/main/java/com/lgtm/easymoney/models/User.java
src/main/java/com/lgtm/easymoney/payload/BalanceReq.java
src/main/java/com/lgtm/easymoney/payload/BalanceRsp.java
src/main/java/com/lgtm/easymoney/payload/ErrorRsp.java
src/main/java/com/lgtm/easymoney/payload/RegisterReq.java
src/main/java/com/lgtm/easymoney/payload/RegisterRsp.java
src/main/java/com/lgtm/easymoney/repositories/AccountRepository.java
src/main/java/com/lgtm/easymoney/repositories/UserRepository.java
src/main/resources/application.properties

Jira links: 
- https://jenniferduan.atlassian.net/browse/ASE-20
- https://jenniferduan.atlassian.net/browse/ASE-21

[T3][p0M][1/n] initial version of register and balance apis

---

src/main/java/com/lgtm/easymoney/controllers/RequestController.java
src/main/java/com/lgtm/easymoney/payload/RequestReq.java
src/main/java/com/lgtm/easymoney/payload/RequestRsp.java
src/main/java/com/lgtm/easymoney/repositories/TransactionRepository.java
src/main/java/com/lgtm/easymoney/services/RequestService.java
src/main/java/com/lgtm/easymoney/services/TransactionService.java
src/main/java/com/lgtm/easymoney/services/UserService.java
src/main/java/com/lgtm/easymoney/services/impl/RequestServiceImpl.java
src/main/java/com/lgtm/easymoney/services/impl/TransactionServiceImpl.java
src/main/java/com/lgtm/easymoney/services/impl/UserServiceImpl.java
src/main/resources/application.properties

This is the sequence of implementation of request API.
1. implement `transactionService`, which is the only service that manipulates the data
2. implement `requestService` which handles request related apis, and it calls `transactionService` to execute stuff
3. controller - create new request
1. I delivered 1, 2, 3 in this PR. 
2. Some refactoring needed but they are not blockers.
(3) is being tested using postman and requests are written to local DB:
1. deliver controller for retrieve all user's requests
4. deliver controller for accepting requests
CC: @howieraem @jenniferduan45 @KenXiong123

[t3][p0L][1/n] request API

---

pom.xml
src/main/java/com/lgtm/easymoney/payload/RegisterReq.java
src/main/java/com/lgtm/easymoney/repositories/UserRepository.java
src/test/java/com/lgtm/easymoney/controllers/AuthControllerTest.java
src/test/java/com/lgtm/easymoney/controllers/UserControllerTest.java
src/test/java/com/lgtm/easymoney/services/UserServiceImplIntegrationTest.java
src/test/java/com/lgtm/easymoney/services/UserServiceImplTest.java
src/test/resources/application.properties

- Add test dependencies
- Started writing controller and service tests

[t3] initialize tests

---

.github/workflows/github-actions-demo.yml
src/main/java/com/lgtm/easymoney/services/impl/RequestServiceImpl.java

setup gh actions to show testing status upon each push.
1. deliver a template for workflows
1. setup cicd
cc @howieraem @jenniferduan45 @KenXiong123

[t3][p1M][1/n] github actions

---

README.md
pom.xml
src/main/java/com/lgtm/easymoney/EasymoneyApplication.java
src/main/java/com/lgtm/easymoney/controllers/AuthController.java
src/main/java/com/lgtm/easymoney/controllers/GroupController.java
src/main/java/com/lgtm/easymoney/controllers/RequestController.java
src/main/java/com/lgtm/easymoney/controllers/SearchController.java
src/main/java/com/lgtm/easymoney/controllers/TransferController.java
src/main/java/com/lgtm/easymoney/controllers/UserController.java
src/main/resources/application.properties

- Added OpenAPI dependencies to automatically generate API documentations
- Added instructions necessary for iter 1 to README

[t3] API documentation setup and README

---

src/test/java/com/lgtm/easymoney/controllers/TransferControllerTest.java
src/test/java/com/lgtm/easymoney/services/GroupServiceImplTest.java
src/test/java/com/lgtm/easymoney/services/impl/GroupServiceImplTest.java
src/test/java/com/lgtm/easymoney/services/impl/UserServiceImplIntegrationTest.java
src/test/java/com/lgtm/easymoney/services/impl/UserServiceImplTest.java

**Goal**
Implement unit test for Transfer API.
**In this PR**
- Implement TransferControllerTest using standard format.
- Refactor previous test file directories.
**Next PR**
- Implement TransferServiceImplTest.
- Probably some other services' unit tests.

[t3][p1L]T3 transfer api test

---

src/main/java/com/lgtm/easymoney/controllers/RequestController.java
src/main/java/com/lgtm/easymoney/enums/validator/ValueOfEnum.java
src/main/java/com/lgtm/easymoney/enums/validator/ValueOfEnumValidator.java
src/main/java/com/lgtm/easymoney/exceptions/DatabaseFailureException.java
src/main/java/com/lgtm/easymoney/exceptions/InvalidUpdateException.java
src/main/java/com/lgtm/easymoney/exceptions/ResourceNotFoundException.java
src/main/java/com/lgtm/easymoney/exceptions/handlers/ControllerExceptionHandler.java
src/main/java/com/lgtm/easymoney/models/Transaction.java
src/main/java/com/lgtm/easymoney/payload/RequestReq.java
src/main/java/com/lgtm/easymoney/payload/TransferReq.java
src/main/java/com/lgtm/easymoney/services/GroupService.java
src/main/java/com/lgtm/easymoney/services/RequestService.java
src/main/java/com/lgtm/easymoney/services/UserService.java
src/main/java/com/lgtm/easymoney/services/impl/GroupServiceImpl.java
src/main/java/com/lgtm/easymoney/services/impl/RequestServiceImpl.java
src/main/java/com/lgtm/easymoney/services/impl/TransactionServiceImpl.java
src/main/java/com/lgtm/easymoney/services/impl/TransferServiceImpl.java
src/main/java/com/lgtm/easymoney/services/impl/UserServiceImpl.java
src/main/resources/data.sql
src/test/java/com/lgtm/easymoney/controllers/RequestControllerTest.java
src/test/java/com/lgtm/easymoney/controllers/TransferControllerTest.java

Fix shit
1. refactor request controller so that response are built at controller level, cleaner at service level.
2. build unit tests for request controller
3. fix styles
1. build an exception handler for cases where can't accept/decline requests. right now using `InvalidUpdate` but i hope it provides more info.
2. if reviewers think testing approach LG, then i'll add more testings for better coverage.
CC: @howieraem

[t3][p0L][1/n] refactoring request API testing

---

src/main/java/com/lgtm/easymoney/enums/validator/ValueOfEnumValidator.java
src/main/java/com/lgtm/easymoney/exceptions/handlers/ControllerExceptionHandler.java
src/main/java/com/lgtm/easymoney/services/impl/UserServiceImpl.java
src/test/java/com/lgtm/easymoney/controllers/GroupControllerTest.java

- Added tests for group controller
- Optimized enum validator
- Fixed the bug of saving biz profile

[T3] group controller test and bug fixes

---

src/main/java/com/lgtm/easymoney/controllers/GroupController.java
src/main/java/com/lgtm/easymoney/payload/GroupAdsRsp.java
src/main/java/com/lgtm/easymoney/services/GroupService.java
src/main/java/com/lgtm/easymoney/services/impl/GroupServiceImpl.java

support ads functionality in groups.
1. added controller path for `getGroupAds`: returns all business users' promotion texts within a group. This is rather a prototype feature after talking with @howieraem so that we have something for multi-client.

[t3][p0M][1/n] group ads

---

src/main/java/com/lgtm/easymoney/controllers/TransferController.java
src/main/java/com/lgtm/easymoney/enums/TransactionStatus.java
src/main/java/com/lgtm/easymoney/services/TransferService.java
src/main/java/com/lgtm/easymoney/services/impl/TransactionServiceImpl.java
src/main/java/com/lgtm/easymoney/services/impl/TransferServiceImpl.java
src/test/java/com/lgtm/easymoney/controllers/TransferControllerTest.java
src/test/java/com/lgtm/easymoney/services/impl/TransferServiceImplTest.java

**Goal**
Implement unit test and refactor logics for Transfer API.
**In this PR**
- Implement TransferServiceTest. 
- Refactor TransferController and its unit test.
- Add some more logic in TransferService, TransactionService, etc.
- All unit tests passed and checkStyle passed.
**Next PR**
- Probably implement part of TransactionServiceTest (because thereare too many and we may need to divide it).

[t3][p1M] transfer-service-test-and-refactor

---

src/main/java/com/lgtm/easymoney/services/impl/TransferServiceImpl.java
src/test/java/com/lgtm/easymoney/services/impl/TransferServiceImplTest.java

[t3]Transfer api quick fix

---

src/main/java/com/lgtm/easymoney/services/impl/TransferServiceImpl.java
src/test/java/com/lgtm/easymoney/services/impl/RequestServiceImplTest.java

1. init some test cases for `requestserviceimpltest`
add tests for `accept/decline`
fuck, there's so much work.

[t3][p1M][1/n] RequestServiceImplTest

---

src/main/java/com/lgtm/easymoney/controllers/SearchController.java
src/test/java/com/lgtm/easymoney/controllers/SearchControllerTest.java

Goal
Implement unit test and refactor logics for Search API.
In this PR
Implement SearchControllerTest.
Refactor SearchController and its unit test.
All unit tests passed.

[t3]-search controller test

---

src/main/java/com/lgtm/easymoney/exceptions/InvalidUpdateException.java
src/main/java/com/lgtm/easymoney/exceptions/ResourceNotFoundException.java
src/main/java/com/lgtm/easymoney/exceptions/handlers/ControllerExceptionHandler.java
src/main/java/com/lgtm/easymoney/models/User.java
src/main/java/com/lgtm/easymoney/services/GroupService.java
src/main/java/com/lgtm/easymoney/services/impl/GroupServiceImpl.java
src/main/java/com/lgtm/easymoney/services/impl/TransferServiceImpl.java
src/test/java/com/lgtm/easymoney/controllers/GroupControllerTest.java
src/test/java/com/lgtm/easymoney/services/impl/GroupServiceImplTest.java
src/test/java/com/lgtm/easymoney/services/impl/UserServiceImplTest.java

- Added group service tests
- Removed unused fields in custom exceptions to improve coverage
- Formatted user service tests
Now group controller and service are both 100% covered.

[t3] group (incl. ads) service test and some simplifications

---

src/main/java/com/lgtm/easymoney/controllers/SearchController.java
src/main/java/com/lgtm/easymoney/services/RequestService.java
src/main/java/com/lgtm/easymoney/services/impl/RequestServiceImpl.java
src/test/java/com/lgtm/easymoney/services/impl/RequestServiceImplTest.java

1. 100% coverage for request service implementation. 
2. removed unused method `getAllRequests` since we already have that in `transactionService`
start working on transaction service impl test

[t3][p0M][2/n] request - 100% coverage for request service impl

---

src/test/java/com/lgtm/easymoney/services/impl/TransactionServiceImplTest.java

**Goal**
Implement unit test for `TransactionServiceImpl`.
**In this PR**
Implement the rest of `TransactionServiceImplTest` followed from PR #36 . Coverage 100%. 
CC: @rl3250 @howieraem @KenXiong123

[t3] complete-transaction-service-unit-test

---

README.md
src/main/java/com/lgtm/easymoney/configs/DbConsts.java
src/main/java/com/lgtm/easymoney/controllers/FriendController.java
src/main/java/com/lgtm/easymoney/controllers/SearchController.java
src/main/java/com/lgtm/easymoney/exceptions/InapplicableOperationException.java
src/main/java/com/lgtm/easymoney/exceptions/InvalidUpdateException.java
src/main/java/com/lgtm/easymoney/exceptions/handlers/ControllerExceptionHandler.java
src/main/java/com/lgtm/easymoney/models/Friendship.java
src/main/java/com/lgtm/easymoney/models/User.java
src/main/java/com/lgtm/easymoney/payload/FriendshipReq.java
src/main/java/com/lgtm/easymoney/payload/ProfileRsp.java
src/main/java/com/lgtm/easymoney/payload/ProfilesRsp.java
src/main/java/com/lgtm/easymoney/repositories/FriendshipRepository.java
src/main/java/com/lgtm/easymoney/services/FriendService.java
src/main/java/com/lgtm/easymoney/services/SearchService.java
src/main/java/com/lgtm/easymoney/services/impl/FriendServiceImpl.java
src/main/java/com/lgtm/easymoney/services/impl/SearchServiceImpl.java
src/main/resources/application.properties
src/test/java/com/lgtm/easymoney/controllers/SearchControllerTest.java
src/test/java/com/lgtm/easymoney/services/impl/SearchServiceImplTest.java

- Implemented friendship APIs and logics: add (request), accept, delete, get accepted and get pending
- Renamed `SearchRsp` to `ProfilesRsp` to reuse this payload
Tested with Postman.

[t3] initial friendship implementation

---

src/main/java/com/lgtm/easymoney/models/User.java
src/test/java/com/lgtm/easymoney/controllers/FriendControllerTest.java

Sorry somehow cannot push local changes in last pr 
Here is the controller test

friend controller test

---

src/main/java/com/lgtm/easymoney/services/FriendService.java
src/main/java/com/lgtm/easymoney/services/impl/FriendServiceImpl.java
src/test/java/com/lgtm/easymoney/services/impl/FriendServiceImplTest.java

Service test in friend.
Relatively high coverage, ignore repetitive control flow block for concision.
Minor refactor in friend service

Friend service test

---

README.md
system_tests.postman_collection.json

Add Postman collection JSON and instructions about how to run.

[t3] postman config and instructions

---

src/main/java/com/lgtm/easymoney/controllers/AuthController.java
src/main/java/com/lgtm/easymoney/controllers/GroupController.java
src/main/java/com/lgtm/easymoney/controllers/UserController.java
src/main/java/com/lgtm/easymoney/services/impl/GroupServiceImpl.java
src/main/java/com/lgtm/easymoney/services/impl/UserServiceImpl.java
src/test/java/com/lgtm/easymoney/EasymoneyApplicationTests.java
src/test/java/com/lgtm/easymoney/controllers/AuthControllerTest.java
src/test/java/com/lgtm/easymoney/controllers/GroupControllerTest.java
src/test/java/com/lgtm/easymoney/controllers/UserControllerTest.java
src/test/java/com/lgtm/easymoney/integrations/DataIntegrityTest.java
src/test/java/com/lgtm/easymoney/services/impl/GroupServiceImplTest.java
src/test/java/com/lgtm/easymoney/services/impl/UserServiceImplTest.java

method comments of auth, user and group services and controllers

[t3] method comments of auth, user and group services and controllers

---

src/main/java/com/lgtm/easymoney/controllers/SearchController.java
src/main/java/com/lgtm/easymoney/payload/ProfilesRsp.java
src/main/java/com/lgtm/easymoney/services/SearchService.java
src/main/java/com/lgtm/easymoney/services/impl/FriendServiceImpl.java
src/main/java/com/lgtm/easymoney/services/impl/SearchServiceImpl.java
src/main/resources/application.properties
src/test/java/com/lgtm/easymoney/controllers/FriendControllerTest.java
src/test/java/com/lgtm/easymoney/controllers/SearchControllerTest.java
src/test/java/com/lgtm/easymoney/services/impl/SearchServiceImplTest.java

remove success in profile res
search by id return one user profile
all tests related to friends and search passed

[t3] - add exception when search user info fails

---

src/main/java/com/lgtm/easymoney/payload/req/BizProfileReq.java
src/test/java/com/lgtm/easymoney/services/impl/FriendServiceImplTest.java
src/test/java/com/lgtm/easymoney/services/impl/GroupServiceImplTest.java
src/test/java/com/lgtm/easymoney/services/impl/RequestServiceImplTest.java
src/test/java/com/lgtm/easymoney/services/impl/TransferServiceImplTest.java
src/test/java/com/lgtm/easymoney/services/impl/UserServiceImplTest.java

Changes:
- Fixed existing service tests due to auth.
- Added new tests to user, friend and group services. The coverage is 100% except for auth, loan and feed services.
TODOs:
- Fix controller tests by mocking auth (this should also cover login() in auth service)
- Add tests for loan and feed services

[t4][4/n] fix service tests

---

src/test/java/com/lgtm/easymoney/controllers/LoanControllerTest.java

**In this PR**
Complete Loan Controller unit test. Controller test coverage now reaches 100%.
**Next PR**
Complete Loan Service unit test.

[t5] Loan Controller Test

---

.github/workflows/github-actions.yml
src/main/java/com/lgtm/easymoney/payload/req/RequestAcceptDeclineReq.java
src/main/java/com/lgtm/easymoney/services/impl/LoanServiceImpl.java
src/test/java/com/lgtm/easymoney/controllers/AnalyticControllerTest.java
src/test/java/com/lgtm/easymoney/controllers/LoanControllerTest.java
src/test/java/com/lgtm/easymoney/controllers/RequestControllerTest.java
src/test/java/com/lgtm/easymoney/services/impl/AnalyticServiceImplTest.java
src/test/java/com/lgtm/easymoney/services/impl/LoanServiceImplTest.java
system_tests.postman_collection.json

Changes:
- Removed unused imports and fixed styles in unit tests of analytic feature
- Removed unused field in `RequestAcceptDeclineReq`
- Saved tokens as Postman collection variables and used them in API tests
- GitHub Actions with API tests

[t5] API tests in CI

---

system_tests.postman_collection.json

Added some assertions to the Postman collection.

[add] assertions in API tests
